# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: turbo_message.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'turbo_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13turbo_message.proto\"5\n\x0fUserCredentials\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\",\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x18\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\"b\n\x04Mail\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\x0e\n\x06sender\x18\x03 \x01(\t\x12\x11\n\trecipient\x18\x04 \x01(\t\x12\x0c\n\x04\x62ody\x18\x05 \x01(\t\x12\x0c\n\x04read\x18\x06 \x01(\x08\"O\n\x0bMailRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x11\n\trecipient\x18\x02 \x01(\t\x12\x0f\n\x07subject\x18\x03 \x01(\t\x12\x0c\n\x04\x62ody\x18\x04 \x01(\t\"&\n\x06MailId\x12\x10\n\x08username\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\" \n\x08MailList\x12\x14\n\x05mails\x18\x01 \x03(\x0b\x32\x05.Mail2\x81\x02\n\x0cTurboMessage\x12+\n\x0cRegisterUser\x12\x10.UserCredentials\x1a\t.Response\x12$\n\x05Login\x12\x10.UserCredentials\x1a\t.Response\x12#\n\x08SendMail\x12\x0c.MailRequest\x1a\t.Response\x12\x1c\n\x08GetInbox\x12\x05.User\x1a\t.MailList\x12\x1d\n\tGetOutbox\x12\x05.User\x1a\t.MailList\x12\x1a\n\x08ReadMail\x12\x07.MailId\x1a\x05.Mail\x12 \n\nDeleteMail\x12\x07.MailId\x1a\t.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'turbo_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERCREDENTIALS']._serialized_start=23
  _globals['_USERCREDENTIALS']._serialized_end=76
  _globals['_RESPONSE']._serialized_start=78
  _globals['_RESPONSE']._serialized_end=122
  _globals['_USER']._serialized_start=124
  _globals['_USER']._serialized_end=148
  _globals['_MAIL']._serialized_start=150
  _globals['_MAIL']._serialized_end=248
  _globals['_MAILREQUEST']._serialized_start=250
  _globals['_MAILREQUEST']._serialized_end=329
  _globals['_MAILID']._serialized_start=331
  _globals['_MAILID']._serialized_end=369
  _globals['_MAILLIST']._serialized_start=371
  _globals['_MAILLIST']._serialized_end=403
  _globals['_TURBOMESSAGE']._serialized_start=406
  _globals['_TURBOMESSAGE']._serialized_end=663
# @@protoc_insertion_point(module_scope)
